added italian translation
grumpycat3051/harbour-phillis pull request #4
Opened 2019-09-30 16:43 UTC by fravaccaro

2019-10-05 01:48 UTC, grumpycat3051 requested changes
Thank you for your contribution. Please translate the rest of the strings.

2019-10-05 01:48 UTC, grumpycat3051 commented on translations/harbour-phillis-it.ts
> +    <message id="ph-settings-page-access-require-pin-label">
What about the rest of the strings?

2019-10-05 18:14 UTC, fravaccaro commented on translations/harbour-phillis-it.ts
> +    <message id="ph-settings-page-access-require-pin-label">
what do you mean?

2019-10-06 16:47 UTC, fravaccaro commented
Done :) I'm sorry if I missed some in the first place

2019-10-07 15:08 UTC, grumpycat3051 commented
Thank you for your help. I have merged your changes. There where some changes to the about page and the newly added translations page that you might want to look at.

2019-10-07 15:08 UTC, closed without merging